-- liquibase formatted sql

-- changeset weare4saken:3
CREATE TABLE avatar (
    id         BIGINT PRIMARY KEY,
    data       BYTEA,
    file_path  VARCHAR(255),
    file_size  BIGINT,
    media_type VARCHAR(255),
    student_id BIGINT REFERENCES student (student_id)
);

-- changeset weare4saken:4
ALTER TABLE avatar RENAME COLUMN student_id TO student_student_id;

-- changeset weare4saken:9
ALTER TABLE avatar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


