-- liquibase formatted sql

-- changeset weare4saken:1
CREATE TABLE faculty(
    faculty_id  BIGINT PRIMARY KEY,
    color       VARCHAR(50) NOT NULL,
    name        VARCHAR(255) UNIQUE NOT NULL
);

-- changeset weare4saken:7
ALTER TABLE faculty ALTER COLUMN faculty_id ADD GENERATED BY DEFAULT AS IDENTITY;
